import {
  Inter,
  Montserrat,
  Lora,
  Josefin_Slab,
  Cardo,
  Caveat,
  Playfair_Display,
  Lexend,
  Love_Light,
  Lovers_Quarrel,
} from "next/font/google";
import "./globals.css";
import { AntThemeProvider } from "./contexts/ThemeProvider";

const lexend = Lexend({
  subsets: ["latin", "latin-ext", "vietnamese"],
});

export const inter = Inter({ subsets: ["latin"], weight: ["variable"] });
export const montserrat = Montserrat({
  subsets: ["cyrillic"],
  weight: ["variable"],
});
export const lora = Lora({ subsets: ["cyrillic"], weight: ["variable"] });
export const cardo = Cardo({ subsets: ["greek"], weight: ["400", "700"] });
export const caveat = Caveat({ subsets: ["cyrillic"], weight: ["variable"] });
export const josephine = Josefin_Slab({
  subsets: ["latin"],
  weight: ["variable"],
});
export const playfair = Playfair_Display({
  subsets: ["cyrillic", "latin", "latin-ext", "vietnamese"],
  weight: ["variable"],
});
export const loveLight = Love_Light({
  subsets: ["latin", "latin-ext", "vietnamese"],
  weight: ["400"],
});
export const loversQuarrel = Lovers_Quarrel({
  subsets: ["latin", "latin-ext", "vietnamese"],
  weight: ["400"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased`}>
        <AntThemeProvider>{children}</AntThemeProvider>
        {/* {children} */}
      </body>
    </html>
  );
}
